#pragma once

#include <string>
#include <vector>
#include <map>
#include <queue>
#include <functional>
#include <mutex>
#include <atomic>
#include <thread>
#include <condition_variable>
#include <chrono>
#include <memory>
#include <random>
#include <set>

namespace powsys365 {

// ---------------------------------------------------------------------------
// Event types for power system simulation
// ---------------------------------------------------------------------------
enum class SimulationEventType {
    FAULT,                  // Short circuit fault
    FAULT_CLEAR,            // Fault clearance
    BREAKER_OPEN,           // Open a breaker
    BREAKER_CLOSE,          // Close a breaker
    LOAD_CHANGE,            // Load variation
    GENERATOR_TRIP,         // Generator outage
    GENERATOR_RESTORE,      // Generator reconnection
    LINE_TRIP,              // Line outage
    LINE_RESTORE,           // Line reconnection
    TRANSFORMER_TAP_CHANGE, // Tap changer operation
    SHUNT_SWITCHING,        // Capacitor/reactor switching
    MOTOR_STARTING,         // Large motor starting
    SETPOINT_CHANGE,        // Control setpoint change
    CUSTOM                  // User-defined event
};

std::string eventTypeToString(SimulationEventType type);

// ---------------------------------------------------------------------------
// Event structure
// ---------------------------------------------------------------------------
struct SimulationEvent {
    uint64_t eventId = 0;
    std::string name;
    std::string description;
    SimulationEventType type;
    std::chrono::steady_clock::time_point scheduledTime;   // absolute time
    std::chrono::steady_clock::time_point triggerTime;     // when it actually fired
    double simulationTimeSec = 0.0;    // simulation time when event occurs
    double durationSec = 0.0;          // duration for temporary events (fault, etc.)
    std::string targetElementId;       // bus, line, generator ID
    std::map<std::string, double> parameters; // event-specific parameters
    bool executed = false;
    bool cancelled = false;
    bool periodic = false;             // repeat event
    double periodSec = 0.0;            // repetition period
    int maxRepetitions = -1;           // -1 = infinite
    int repetitionCount = 0;
    uint64_t parentEventId = 0;        // for events generated by periodic parents

    // Priority: lower value = higher priority
    int priority = 5;
};

// ---------------------------------------------------------------------------
// Event priority comparator (for priority queue)
// ---------------------------------------------------------------------------
struct EventPriorityCompare {
    bool operator()(const SimulationEvent& a, const SimulationEvent& b) const {
        if (a.priority != b.priority) return a.priority > b.priority;
        return a.scheduledTime > b.scheduledTime;
    }
};

// ---------------------------------------------------------------------------
// Event callback signature
// ---------------------------------------------------------------------------
using EventCallback = std::function<void(const SimulationEvent& event)>;
using EventPrecondition = std::function<bool(const SimulationEvent& event)>;

// ---------------------------------------------------------------------------
// Event filter for querying
// ---------------------------------------------------------------------------
struct EventFilter {
    std::set<SimulationEventType> types;
    std::set<std::string> targetElements;
    double timeRangeStartSec = 0.0;
    double timeRangeEndSec = -1.0; // -1 = no limit
    bool includeExecuted = true;
    bool includePending = true;
    bool includeCancelled = false;
};

// ---------------------------------------------------------------------------
// Event statistics
// ---------------------------------------------------------------------------
struct EventSchedulerStats {
    uint64_t totalEventsScheduled = 0;
    uint64_t totalEventsExecuted = 0;
    uint64_t totalEventsCancelled = 0;
    uint64_t totalPeriodicEvents = 0;
    uint64_t eventsInQueue = 0;
    double averageExecutionDelayMs = 0.0;
    std::map<SimulationEventType, uint64_t> eventsByType;
    std::chrono::steady_clock::time_point startTime;
};

// ---------------------------------------------------------------------------
// Event Scheduler
// ---------------------------------------------------------------------------
class EventScheduler {
public:
    EventScheduler();
    ~EventScheduler();

    // Lifecycle
    void start();
    void stop();
    bool isRunning() const;

    // Event scheduling
    uint64_t scheduleEvent(const SimulationEvent& event);
    uint64_t scheduleEvent(double simulationTimeSec, SimulationEventType type,
                            const std::string& targetElementId,
                            const std::string& name,
                            const std::string& description,
                            const std::map<std::string, double>& params = {},
                            int priority = 5);
    uint64_t schedulePeriodicEvent(double startTimeSec, double periodSec,
                                     SimulationEventType type,
                                     const std::string& targetElementId,
                                     const std::string& name,
                                     int maxRepetitions = -1,
                                     int priority = 5);
    uint64_t scheduleRelativeEvent(double offsetSec, SimulationEventType type,
                                     const std::string& targetElementId,
                                     const std::string& name,
                                     const std::map<std::string, double>& params = {},
                                     int priority = 5);

    // Event management
    bool cancelEvent(uint64_t eventId);
    bool rescheduleEvent(uint64_t eventId, double newSimulationTimeSec);
    std::optional<SimulationEvent> getEvent(uint64_t eventId) const;
    std::vector<SimulationEvent> getPendingEvents() const;
    std::vector<SimulationEvent> getExecutedEvents() const;
    std::vector<SimulationEvent> getFilteredEvents(const EventFilter& filter) const;

    // Callbacks
    void setEventCallback(SimulationEventType type, EventCallback callback);
    void setGlobalCallback(EventCallback callback);
    void setPrecondition(SimulationEventType type, EventPrecondition precondition);
    void removeCallback(SimulationEventType type);

    // Clock sync
    void setSimulationTime(double currentSimTimeSec);
    double getSimulationTime() const;
    void setRealTimeMode(bool realTime);
    bool isRealTimeMode() const;

    // Statistics
    EventSchedulerStats getStats() const;
    void resetStats();

    // Utility
    void clearAllEvents();
    void clearExecutedEvents();
    size_t getQueueSize() const;

    // Random event generation (for Monte Carlo)
    uint64_t scheduleRandomEvent(double timeMinSec, double timeMaxSec,
                                   SimulationEventType type,
                                   const std::string& targetElementId,
                                   const std::string& name);

private:
    void schedulerLoop();
    void executeEvent(const SimulationEvent& event);
    uint64_t generateEventId();
    void handlePeriodicEvent(const SimulationEvent& parent);

    // Priority queue of pending events
    std::priority_queue<SimulationEvent, std::vector<SimulationEvent>, EventPriorityCompare> m_eventQueue;
    mutable std::mutex m_queueMutex;

    // Event registry
    std::map<uint64_t, SimulationEvent> m_eventRegistry;
    mutable std::mutex m_registryMutex;

    // Executed events history
    std::vector<SimulationEvent> m_executedEvents;
    mutable std::mutex m_historyMutex;

    // Callbacks
    std::map<SimulationEventType, EventCallback> m_callbacks;
    EventCallback m_globalCallback;
    std::map<SimulationEventType, EventPrecondition> m_preconditions;
    mutable std::mutex m_callbacksMutex;

    // Time
    std::atomic<double> m_currentSimulationTime{0.0};
    std::atomic<bool> m_realTimeMode{false};

    // Threading
    std::atomic<bool> m_running{false};
    std::thread m_schedulerThread;
    std::condition_variable m_queueCv;

    // ID generation
    std::atomic<uint64_t> m_nextEventId{1};

    // Random generator
    std::mt19937 m_randomGen{std::random_device{}()};

    // Statistics
    mutable std::mutex m_statsMutex;
    EventSchedulerStats m_stats;
};

} // namespace powsys365
